# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-27 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCOUNT_NUMBER', models.IntegerField()),
                ('SIGNATURE_URLS', models.CharField(max_length=256)),
                ('picture', models.ImageField(upload_to='Signatures/')),
            ],
        ),
    ]
